"""
OAuth Routes — handles login, callback, and logout.

Drop this into your FastAPI app:
    from oauth_routes import router as oauth_router
    app.include_router(oauth_router)

Generated by: oauth-for-dummies
Docs: https://github.com/pranavkumaarofficial/oauth-for-dummies
"""

from __future__ import annotations

import secrets
from urllib.parse import urlencode

import httpx
from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import RedirectResponse

from oauth_config import OAUTH_PROVIDERS, OAUTH_BASE_URL

router = APIRouter(prefix="/auth", tags=["auth"])

# In-memory state + session storage (swap for Redis/DB in production)
_pending_states: dict[str, str] = {}
_sessions: dict[str, dict] = {}


def get_session(request: Request) -> dict | None:
    """Get the current user session from the request cookie."""
    session_id = request.cookies.get("session_id")
    if session_id:
        return _sessions.get(session_id)
    return None


@router.get("/{provider}/login")
async def login(provider: str):
    """Redirect the user to the OAuth provider's login page."""
    config = OAUTH_PROVIDERS.get(provider)
    if not config:
        raise HTTPException(status_code=404, detail=f"Unknown provider: {provider}")

    state = secrets.token_urlsafe(32)
    _pending_states[state] = provider

    params = {
        "client_id": config["client_id"],
        "redirect_uri": f"{OAUTH_BASE_URL}/auth/{provider}/callback",
        "scope": " ".join(config["scopes"]),
        "state": state,
        "response_type": "code",
    }
    return RedirectResponse(f"{config['authorize_url']}?{urlencode(params)}")


@router.get("/{provider}/callback")
async def callback(provider: str, code: str = "", state: str = ""):
    """Handle the OAuth callback — exchange code for token, fetch user info."""
    saved_provider = _pending_states.pop(state, None)
    if saved_provider is None or saved_provider != provider:
        raise HTTPException(status_code=400, detail="Invalid state. Try logging in again.")

    if not code:
        raise HTTPException(status_code=400, detail="No authorization code received.")

    config = OAUTH_PROVIDERS.get(provider)
    if not config:
        raise HTTPException(status_code=404, detail=f"Unknown provider: {provider}")

    # Exchange code for access token
    async with httpx.AsyncClient() as client:
        token_resp = await client.post(
            config["token_url"],
            data={
                "client_id": config["client_id"],
                "client_secret": config["client_secret"],
                "code": code,
                "redirect_uri": f"{OAUTH_BASE_URL}/auth/{provider}/callback",
                "grant_type": "authorization_code",
            },
            headers={"Accept": "application/json"},
        )
        token_resp.raise_for_status()
        token_data = token_resp.json()

    access_token = token_data["access_token"]

    # Fetch user info
    async with httpx.AsyncClient() as client:
        user_resp = await client.get(
            config["userinfo_url"],
            headers={"Authorization": f"Bearer {access_token}"},
        )
        user_resp.raise_for_status()
        raw_user = user_resp.json()

    # Normalize user data across providers
    if provider == "github":
        user = {
            "id": str(raw_user["id"]),
            "name": raw_user.get("name") or raw_user.get("login", ""),
            "email": raw_user.get("email"),
            "avatar": raw_user.get("avatar_url"),
            "provider": provider,
        }
        # GitHub sometimes hides email — try the emails endpoint
        if not user["email"]:
            try:
                async with httpx.AsyncClient() as email_client:
                    emails_resp = await email_client.get(
                        "https://api.github.com/user/emails",
                        headers={"Authorization": f"Bearer {access_token}"},
                    )
                if emails_resp.status_code == 200:
                    primary = next(
                        (e for e in emails_resp.json() if e.get("primary")), None
                    )
                    if primary:
                        user["email"] = primary["email"]
            except Exception:
                pass
    elif provider == "google":
        user = {
            "id": str(raw_user["id"]),
            "name": raw_user.get("name", ""),
            "email": raw_user.get("email"),
            "avatar": raw_user.get("picture"),
            "provider": provider,
        }
    else:
        user = {
            "id": str(raw_user.get("id", "")),
            "name": raw_user.get("name", ""),
            "email": raw_user.get("email"),
            "avatar": raw_user.get("avatar", raw_user.get("picture")),
            "provider": provider,
        }

    # Create session
    session_id = secrets.token_urlsafe(32)
    _sessions[session_id] = user

    response = RedirectResponse(url="/profile", status_code=303)
    response.set_cookie(
        key="session_id",
        value=session_id,
        httponly=True,
        max_age=3600,
        samesite="lax",
    )
    return response


@router.get("/logout")
async def logout(request: Request):
    """Clear the session and redirect home."""
    session_id = request.cookies.get("session_id")
    if session_id:
        _sessions.pop(session_id, None)

    response = RedirectResponse(url="/", status_code=303)
    response.delete_cookie("session_id")
    return response
