"""
OAuth Routes — handles login, callback, and logout.

Supports OAuth 2.0 (client_secret) and OAuth 2.1 (PKCE).
Drop this into your FastAPI app:
    from oauth_routes import router as oauth_router
    app.include_router(oauth_router)

Generated by: oauth-for-dummies
Docs: https://github.com/pranavkumaarofficial/oauth-for-dummies
"""

from __future__ import annotations

import hashlib
import base64
import secrets
from urllib.parse import urlencode

import httpx
from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import RedirectResponse

from oauth_config import OAUTH_PROVIDERS, OAUTH_BASE_URL

router = APIRouter(prefix="/auth", tags=["auth"])

# In-memory state + session storage (swap for Redis/DB in production)
_pending_states: dict[str, str] = {}
_code_verifiers: dict[str, str] = {}  # PKCE: state -> code_verifier
_sessions: dict[str, dict] = {}

# Providers that support/require PKCE (add provider keys here to enable)
PKCE_PROVIDERS: set[str] = set()


# ---- PKCE helpers ----

def _generate_code_verifier() -> str:
    return secrets.token_urlsafe(64)


def _generate_code_challenge(verifier: str) -> str:
    digest = hashlib.sha256(verifier.encode("ascii")).digest()
    return base64.urlsafe_b64encode(digest).rstrip(b"=").decode("ascii")


# ---- User info normalizers ----

def _normalize_user(provider: str, raw: dict, access_token: str | None = None) -> dict:
    """Normalize provider-specific user data into a standard shape."""
    if provider == "github":
        user = {
            "id": str(raw["id"]),
            "name": raw.get("name") or raw.get("login", ""),
            "email": raw.get("email"),
            "avatar": raw.get("avatar_url"),
            "provider": provider,
        }
        # GitHub sometimes hides email — try the emails endpoint
        if not user["email"] and access_token:
            try:
                resp = httpx.get(
                    "https://api.github.com/user/emails",
                    headers={"Authorization": f"Bearer {access_token}"},
                )
                if resp.status_code == 200:
                    primary = next((e for e in resp.json() if e.get("primary")), None)
                    if primary:
                        user["email"] = primary["email"]
            except Exception:
                pass
        return user

    elif provider == "google":
        return {
            "id": str(raw["id"]),
            "name": raw.get("name", ""),
            "email": raw.get("email"),
            "avatar": raw.get("picture"),
            "provider": provider,
        }

    elif provider == "discord":
        avatar_hash = raw.get("avatar")
        user_id = raw["id"]
        avatar_url = None
        if avatar_hash:
            avatar_url = f"https://cdn.discordapp.com/avatars/{user_id}/{avatar_hash}.png"
        return {
            "id": str(user_id),
            "name": raw.get("global_name") or raw.get("username", ""),
            "email": raw.get("email"),
            "avatar": avatar_url,
            "provider": provider,
        }

    elif provider == "spotify":
        images = raw.get("images", [])
        return {
            "id": str(raw["id"]),
            "name": raw.get("display_name") or "",
            "email": raw.get("email"),
            "avatar": images[0]["url"] if images else None,
            "provider": provider,
        }

    elif provider == "microsoft":
        return {
            "id": str(raw["id"]),
            "name": raw.get("displayName") or "",
            "email": raw.get("mail") or raw.get("userPrincipalName"),
            "avatar": None,
            "provider": provider,
        }

    elif provider == "linkedin":
        return {
            "id": str(raw.get("sub", "")),
            "name": raw.get("name") or "",
            "email": raw.get("email"),
            "avatar": raw.get("picture"),
            "provider": provider,
        }

    else:
        return {
            "id": str(raw.get("id", "")),
            "name": raw.get("name", ""),
            "email": raw.get("email"),
            "avatar": raw.get("avatar", raw.get("picture")),
            "provider": provider,
        }


def get_session(request: Request) -> dict | None:
    """Get the current user session from the request cookie."""
    session_id = request.cookies.get("session_id")
    if session_id:
        return _sessions.get(session_id)
    return None


@router.get("/{provider}/login")
async def login(provider: str):
    """Redirect the user to the OAuth provider's login page."""
    config = OAUTH_PROVIDERS.get(provider)
    if not config:
        raise HTTPException(status_code=404, detail=f"Unknown provider: {provider}")

    state = secrets.token_urlsafe(32)
    _pending_states[state] = provider

    params = {
        "client_id": config["client_id"],
        "redirect_uri": f"{OAUTH_BASE_URL}/auth/{provider}/callback",
        "scope": " ".join(config["scopes"]),
        "state": state,
        "response_type": "code",
    }

    # PKCE: add code_challenge if enabled for this provider
    if provider in PKCE_PROVIDERS:
        verifier = _generate_code_verifier()
        _code_verifiers[state] = verifier
        params["code_challenge"] = _generate_code_challenge(verifier)
        params["code_challenge_method"] = "S256"

    return RedirectResponse(f"{config['authorize_url']}?{urlencode(params)}")


@router.get("/{provider}/callback")
async def callback(provider: str, code: str = "", state: str = ""):
    """Handle the OAuth callback — exchange code for token, fetch user info."""
    saved_provider = _pending_states.pop(state, None)
    if saved_provider is None or saved_provider != provider:
        raise HTTPException(status_code=400, detail="Invalid state. Try logging in again.")

    if not code:
        raise HTTPException(status_code=400, detail="No authorization code received.")

    config = OAUTH_PROVIDERS.get(provider)
    if not config:
        raise HTTPException(status_code=404, detail=f"Unknown provider: {provider}")

    # Build token exchange request
    token_data = {
        "client_id": config["client_id"],
        "code": code,
        "redirect_uri": f"{OAUTH_BASE_URL}/auth/{provider}/callback",
        "grant_type": "authorization_code",
    }

    # PKCE: send code_verifier instead of client_secret
    code_verifier = _code_verifiers.pop(state, None)
    if code_verifier:
        token_data["code_verifier"] = code_verifier
    else:
        token_data["client_secret"] = config["client_secret"]

    # Exchange code for access token
    async with httpx.AsyncClient() as client:
        token_resp = await client.post(
            config["token_url"],
            data=token_data,
            headers={"Accept": "application/json"},
        )
        token_resp.raise_for_status()
        token_json = token_resp.json()

    access_token = token_json["access_token"]

    # Fetch user info
    async with httpx.AsyncClient() as client:
        user_resp = await client.get(
            config["userinfo_url"],
            headers={"Authorization": f"Bearer {access_token}"},
        )
        user_resp.raise_for_status()
        raw_user = user_resp.json()

    # Normalize user data
    user = _normalize_user(provider, raw_user, access_token)

    # Create session
    session_id = secrets.token_urlsafe(32)
    _sessions[session_id] = user

    response = RedirectResponse(url="/profile", status_code=303)
    response.set_cookie(
        key="session_id",
        value=session_id,
        httponly=True,
        max_age=3600,
        samesite="lax",
    )
    return response


@router.get("/logout")
async def logout(request: Request):
    """Clear the session and redirect home."""
    session_id = request.cookies.get("session_id")
    if session_id:
        _sessions.pop(session_id, None)

    response = RedirectResponse(url="/", status_code=303)
    response.delete_cookie("session_id")
    return response
