"""
Example FastAPI app with OAuth login — generated by oauth-for-dummies.

Run:  uvicorn oauth_example_app:app --reload
Open: http://localhost:8000

Docs: https://github.com/pranavkumaarofficial/oauth-for-dummies
"""

from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse

from oauth_config import OAUTH_PROVIDERS
from oauth_routes import router as oauth_router, get_session

app = FastAPI(title="My App")
app.include_router(oauth_router)


LOGIN_PAGE = """
<!DOCTYPE html>
<html>
<head><title>Login</title>
<style>
  body {{ font-family: system-ui, sans-serif; max-width: 480px; margin: 60px auto; text-align: center; }}
  a.btn {{ display: inline-block; margin: 8px; padding: 12px 24px; background: #24292e;
           color: white; text-decoration: none; border-radius: 6px; font-size: 16px; }}
  a.btn:hover {{ opacity: 0.85; }}
  .provider-google {{ background: #4285f4; }}
</style>
</head>
<body>
  <h1>Welcome</h1>
  <p>Choose a login method:</p>
  {buttons}
  {user_info}
</body>
</html>
"""

PROFILE_PAGE = """
<!DOCTYPE html>
<html>
<head><title>Profile</title>
<style>
  body {{ font-family: system-ui, sans-serif; max-width: 480px; margin: 60px auto; text-align: center; }}
  img {{ width: 80px; height: 80px; border-radius: 50%; }}
  a {{ color: #e74c3c; }}
</style>
</head>
<body>
  <img src="{avatar}" alt="avatar" />
  <h1>{name}</h1>
  <p>{email}</p>
  <p>Logged in via <strong>{provider}</strong></p>
  <p><a href="/auth/logout">Logout</a></p>
</body>
</html>
"""


@app.get("/", response_class=HTMLResponse)
async def home(request: Request):
    user = get_session(request)
    buttons = ""
    for key, cfg in OAUTH_PROVIDERS.items():
        css_class = f"provider-{key}" if key != "github" else ""
        buttons += f'<a class="btn {css_class}" href="/auth/{key}/login">{cfg["icon"]} Login with {cfg["name"]}</a>\n'

    user_info = ""
    if user:
        user_info = f'<p>Logged in as <strong>{user["name"]}</strong> — <a href="/profile">Profile</a> | <a href="/auth/logout">Logout</a></p>'

    return LOGIN_PAGE.format(buttons=buttons, user_info=user_info)


@app.get("/profile", response_class=HTMLResponse)
async def profile(request: Request):
    user = get_session(request)
    if not user:
        return HTMLResponse("<p>Not logged in. <a href='/'>Go back</a></p>", status_code=401)

    return PROFILE_PAGE.format(
        name=user.get("name", ""),
        email=user.get("email", ""),
        avatar=user.get("avatar", ""),
        provider=user.get("provider", ""),
    )
