"""
OAuth Configuration — loads provider credentials from environment variables.

Generated by: oauth-for-dummies
Docs: https://github.com/pranavkumaarofficial/oauth-for-dummies
"""

import os
from dotenv import load_dotenv

load_dotenv()

OAUTH_PROVIDERS = {}

# --- GitHub ---
if os.getenv("GITHUB_CLIENT_ID"):
    OAUTH_PROVIDERS["github"] = {
        "client_id": os.getenv("GITHUB_CLIENT_ID", ""),
        "client_secret": os.getenv("GITHUB_CLIENT_SECRET", ""),
        "authorize_url": "https://github.com/login/oauth/authorize",
        "token_url": "https://github.com/login/oauth/access_token",
        "userinfo_url": "https://api.github.com/user",
        "scopes": ["read:user", "user:email"],
        "icon": "\U0001f419",
        "name": "GitHub",
    }

# --- Google ---
if os.getenv("GOOGLE_CLIENT_ID"):
    OAUTH_PROVIDERS["google"] = {
        "client_id": os.getenv("GOOGLE_CLIENT_ID", ""),
        "client_secret": os.getenv("GOOGLE_CLIENT_SECRET", ""),
        "authorize_url": "https://accounts.google.com/o/oauth2/v2/auth",
        "token_url": "https://oauth2.googleapis.com/token",
        "userinfo_url": "https://www.googleapis.com/oauth2/v2/userinfo",
        "scopes": [
            "openid",
            "https://www.googleapis.com/auth/userinfo.email",
            "https://www.googleapis.com/auth/userinfo.profile",
        ],
        "icon": "\U0001f535",
        "name": "Google",
    }

# Base URL for building redirect URIs
OAUTH_BASE_URL = os.getenv("OAUTH_BASE_URL", "http://localhost:8000")
OAUTH_SECRET_KEY = os.getenv("APP_SECRET_KEY", "change-me")
